name: Deploy Streaming Proxy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_PROXY_ROLE }}
          aws-region: us-east-1

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM project
        run: sam build --template-file infra/cloudfront/template.yaml

      - name: Deploy to AWS
        run: |
            sam deploy \
            --template-file infra/cloudfront/template.yaml \
            --stack-name synvya-stream-proxy \
            --s3-bucket ${{ secrets.SAM_DEPLOY_BUCKET }} \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --no-confirm-changeset \
            --region us-east-1

      - name: Notify
        run: echo "Deployment of Streaming Proxy completed."