name: Deploy Streaming Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_PROXY_ROLE }}
          aws-region: us-east-1

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Node.js Dependencies
        run: |
          cd infra/sam
          npm install

      - name: Build SAM project
        run: sam build --template-file infra/cloudfront/template.yaml

      - name: Deploy to AWS
        run: |
            sam deploy \
            --template-file infra/cloudfront/template.yaml \
            --stack-name synvya-stream-proxy \
            --s3-bucket ${{ secrets.SAM_DEPLOY_BUCKET }} \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --no-confirm-changeset \
            --region us-east-1 \
            --force-upload

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Verify Proxy Health
        run: |
          curl --fail --silent https://proxy.synvya.com/health

      - name: Notify
        run: echo "Deployment of Streaming Proxy completed."