name: API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Add any required services here (e.g., databases)
      pass:
        image: hello-world

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set environment variables
      run: |
        echo "API_KEY=test_api_key_ci" >> $GITHUB_ENV
        echo "ENVIRONMENT=test" >> $GITHUB_ENV
    
    - name: Start API server
      run: |
        python run_local.py &
        echo $! > server.pid
        # Wait for server to start
        sleep 10
    
    - name: Wait for server to be ready
      run: |
        # Wait up to 30 seconds for server to be ready
        for i in {1..30}; do
          if curl -f http://127.0.0.1:8080/health; then
            echo "Server is ready"
            break
          fi
          echo "Waiting for server... attempt $i"
          sleep 1
        done
    
    - name: Run API tests
      run: |
        python run_tests.py
    
    - name: Stop server
      if: always()
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid) || true
        fi
        pkill -f "python run_local.py" || true 