AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30

Resources:

  StreamProxyFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stream-proxy.handler
      CodeUri: ../sam/
      Role: arn:aws:iam::122610503853:role/synvya-api-proxy-lambda-role-production
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          SYNVYA_API_KEY: '{{resolve:secretsmanager:synvya-api-keys-production:SecretString:SYNVYA_API_KEY}}'
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:us-east-1:122610503853:secret:synvya-api-keys-production-ofo5Nu

  StreamProxyURL:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref StreamProxyFn
      AuthType: NONE
      InvokeMode: RESPONSE_STREAM

  StreamProxyPerm:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StreamProxyFn
      Principal: "*"
      Action: lambda:InvokeFunctionUrl
      FunctionUrlAuthType: NONE

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true

        Origins:
          - Id: FastAPIOrigin
            DomainName: api.synvya.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only

          - Id: LambdaProxyOrigin
            DomainName: !Select [2, !Split ["/", !GetAtt StreamProxyURL.FunctionUrl]]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only

        CacheBehaviors:
          - PathPattern: /health
            TargetOriginId: FastAPIOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [HEAD, GET]
            CachePolicyId: 413fdacd-50ea-4b8f-bcd1-9a2067059475  # AWS managed policy to disable caching

          - PathPattern: /api/*
            TargetOriginId: LambdaProxyOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachePolicyId: 413fdacd-50ea-4b8f-bcd1-9a2067059475


        DefaultCacheBehavior:
          TargetOriginId: LambdaProxyOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachePolicyId: 413fdacd-50ea-4b8f-bcd1-9a2067059475

        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:122610503853:certificate/91f5d0f5-59e6-4519-b8e0-0c6ec946ec64
          SslSupportMethod: sni-only

        Aliases:
          - proxy.synvya.com

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: "synvya.com."
      Name: proxy.synvya.com
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName